male(kelvin).
male(john).
male(williams).
male(ibrahim).
female(teefah).
female(sheedah).
female(cardi).
female(ozozahuwa).
parent(kelvin,john).
parent(kelvin,teefah).
parent(john,willaims).
parent(john,sheedah).
mother(cardi,sheedah).
parent(cardi,sheedah).
mother(cardi,sheedah):-parent(cardi,sheedah),female(cardi).
siblings(A,B):-parent_of(X,A),parent_of(X,B),\=(A,B).
ancestor_of(X,Y):-parent_of(X,Y).
ancestor_of(X,Y):-parent_of(X,Z),ancestor_of(Z,Y).